---
- hosts: azure-linux-vm
  become: true
  become_user: root
  become_method: sudo
  vars:
    unseal_keys_dir_output: "{{ playbook_dir }}/unsealKey"
    root_token_dir_output: "{{ playbook_dir }}/rootKey"
  roles:
    - vault
    - vault-init
    - vault-unseal
    - vault-configure
    - nginx